name: Invitation
version: ${version}
main: io.github.ganyuke.invitation.Invitation
api-version: 1.17

commands:
  invite:
    description: Add a player to the whitelist.
    usage: /invite <player>
    permission: invite.use
  uninvite:
    description: Revokes your most recent invite in the past configured seconds.
    usage: /uninvite
    permission: invite.use
  invitelog:
    description: Show invite logs (recent, or sent/recieved for a player with pages).
    usage: /invitelog [recent [page]] OR /invitelog <sent|recieved> <player> [page]
    permission: invite.log

permissions:
  invite.use:
    description: Allows using /invite
    default: true
  invite.log:
    description: Allows using /invitelog
    default: op
