plugins {
    id 'java-library'
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(java_version)
    withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
    options.release = 16
}

repositories {
    mavenCentral()
}

dependencies {
    // depends on what was shipped with Spigot for Minecraft 1.17
    compileOnly 'com.google.code.gson:gson:2.8.0'
    compileOnly 'org.xerial:sqlite-jdbc:3.34.0'
}

jar {
    manifest {
        attributes([
                'Specification-Title'  : mod_name,
                'Specification-Vendor' : mod_author,
                'Specification-Version': project.version,
                'Implementation-Title' : project.name,
                'Implementation-Version': project.version
        ])
    }
}
